version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
  pre_build:
    commands:
      - echo Install dependencies...
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - echo Running unit tests...
      - npm run test:run
      - echo Running tests with coverage...
      - npm run test:coverage
      - echo Building application...
      - npm run build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post-build phase...
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  name: matteo-frontend-artifacts